SPDU_TYPES = {
    0x01: 'DATA TRANSFER (DT) SPDU',
    0x0d: 'CONNECT (CN) SPDU',
    0x0e: 'ACCEPT (AC) SPDU',
}

SPDU_PARAMETER_TYPES = {
    0x01: 'Connection Identifier',
    0x05: 'Connect Accept Item',
    0x09: 'Called SS user Reference',
    0x0a: 'Calling SS user Reference',
    0x0b: 'Common Reference',
    0x0c: 'Additional Reference Information',
    0x0f: 'Sync Type Item',
    0x10: 'Token Item',
    0x11: 'Transport Disconnect',
    0x13: 'Protocol Options',
    0x14: 'Session Requirement',
    0x15: 'TSDU Maximum Size',
    0x16: 'Version Number',
    0x17: 'Initial Serial Number',
    0x18: 'Prepare Type',
    0x19: 'Enclosure Item',
    0x1a: 'Token Setting Item',
    0x1b: 'Resync Type',
    0x21: 'Linking Information',
    0x29: 'Activity Identifier',
    0x2a: 'Serial Number',
    0x31: 'Reflect Parameter',
    0x32: 'Reason Code',
    0x33: 'Calling Session Selector',
    0x34: 'Called Session Selector',
    0x35: 'Second Resync Type',
    0x36: 'Second Serial Number',
    0x37: 'Second Initial Serial Number',
    0x38: 'Upper Limit Serial Number',
    0x39: 'Large Initial Serial Number',
    0x3a: 'Large Second Initial Serial Number',
    0x3d: 'Data Overflow',
    0xc1: 'Session user data',
    0xc2: 'Session extended user data'
}